spring:
  application:
    name: flight-booking

  datasource:
    url: jdbc:h2:mem:flightdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  main:
    banner-mode: off
  doc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api

auth0:
  domain: "your-auth0-domain.auth0.com"  # e.g., "dev-xyz.us.auth0.com"
  client-id: "your-client-id"           # Obtain from Auth0 dashboard
  client-secret: "your-client-secret"   # Obtain from Auth0 dashboard
  audience: "https://your-api-audience" # e.g., "https://flight-booking-api"

jwt:
  secret: "your-jwt-secret-key"         # A strong secret key (optional if using Auth0)
  expiration: 86400000                  # 24 hours in milliseconds

logging:
  level:
    root: INFO
    org.hibernate: DEBUG
    edu.miu.cs.cs425: DEBUG